# Generated by Django 5.0 on 2023-12-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
    ]
